#!/bin/sh
# pre-push gets executes before every git push command

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
$SCRIPTPATH/actions/branch-name
$SCRIPTPATH/actions/newlines
$SCRIPTPATH/actions/golangci-lint
