#!/bin/sh

files=$(find . -type f -print0 | xargs -0 -L1 bash -c 'test "$(tail -c 1 "$0")" && echo $0')

for file in $files; do
  if ! echo $file | grep '.git/' >/dev/null; then
  echo "Adding newline to $file"
  echo "" >> $file
  fi
done
