#!/bin/sh
# newlines will append a newline to any text not in .git or vendor if a trailing newline is missing

files=$(find . -type f -not -path "./.git/*" -prune -not -path "*/vendor/*" -prune)

for f in $files; do
  if ! echo $f | grep '\|vendor\|.idea\|.git/' >/dev/null; then
    if file $f | grep 'ASCII\|UTF-8' >/dev/null; then
      if test "$(tail -c 1 "$f")" >/dev/null; then
        echo "Adding newline to $f"
        echo "" >>$f
      fi
    fi &
  fi
done
