#!/bin/sh

files=$(find . -type f -print0 | xargs -0 -L1 bash -c 'test "$(tail -c 1 "$0")" && echo $0')

for f in $files; do
  if ! echo $f | grep '\|vendor\|.idea' >/dev/null; then
    if file $f | grep 'ASCII\|UTF-8'; then
      echo "Adding newline to $f"
      echo "" >>$f
    fi
  fi
done
